//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysticLegendsClient.Resources {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemIcons() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MysticLegendsClient.Resources.ItemIcons", typeof(ItemIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/armor/Full_Chainmail_inventory_icon.png.
        /// </summary>
        internal static string bodyArmor_ayreimWarrior {
            get {
                return ResourceManager.GetString("bodyArmor/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/boots/Vaal_Greaves_inventory_icon.png.
        /// </summary>
        internal static string boots_ayreimWarrior {
            get {
                return ResourceManager.GetString("boots/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/gloves/Antique_Gauntlets_inventory_icon.png.
        /// </summary>
        internal static string gloves_ayreimWarrior {
            get {
                return ResourceManager.GetString("gloves/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/helmet/Close_Helmet_inventory_icon.png.
        /// </summary>
        internal static string helmet_ayreimWarrior {
            get {
                return ResourceManager.GetString("helmet/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/potions/Greater_Life_Flask_inventory_icon.png.
        /// </summary>
        internal static string potion_mediumHealth {
            get {
                return ResourceManager.GetString("potion/mediumHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/potions/small_dexterity.png.
        /// </summary>
        internal static string potion_smallDexterity {
            get {
                return ResourceManager.GetString("potion/smallDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/potions/Large_Life_Flask_inventory_icon.png.
        /// </summary>
        internal static string potion_smallHealth {
            get {
                return ResourceManager.GetString("potion/smallHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/potions/small_strength.png.
        /// </summary>
        internal static string potion_smallStrength {
            get {
                return ResourceManager.GetString("potion/smallStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/horn.png.
        /// </summary>
        internal static string regular_goatHorn {
            get {
                return ResourceManager.GetString("regular/goatHorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/fang.png.
        /// </summary>
        internal static string regular_wolveFang {
            get {
                return ResourceManager.GetString("regular/wolveFang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/weapon/Legion_Sword_inventory_icon.png.
        /// </summary>
        internal static string weapon_aresBlade {
            get {
                return ResourceManager.GetString("weapon/aresBlade", resourceCulture);
            }
        }
    }
}
