//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysticLegendsClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemIcons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MysticLegendsClient.Resources.ItemIcons", typeof(ItemIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /items/armor/Full_Chainmail_inventory_icon.png.
        /// </summary>
        internal static string bodyArmor_ayreimWarrior {
            get {
                return ResourceManager.GetString("bodyArmor/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /items/boots/Vaal_Greaves_inventory_icon.png.
        /// </summary>
        internal static string boots_ayreimWarrior {
            get {
                return ResourceManager.GetString("boots/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /items/gloves/Antique_Gauntlets_inventory_icon.png.
        /// </summary>
        internal static string gloves_ayreimWarrior {
            get {
                return ResourceManager.GetString("gloves/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /items/helmet/Close_Helmet_inventory_icon.png.
        /// </summary>
        internal static string helmet_ayreimWarrior {
            get {
                return ResourceManager.GetString("helmet/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /items/potions/Large_Life_Flask_inventory_icon.png.
        /// </summary>
        internal static string potion_smallHealth {
            get {
                return ResourceManager.GetString("potion/smallHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string weapon_aresBlade {
            get {
                return ResourceManager.GetString("weapon/aresBlade", resourceCulture);
            }
        }
    }
}
