//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysticLegendsClient.Resources {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemIcons() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MysticLegendsClient.Resources.ItemIcons", typeof(ItemIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/armor/Full_Chainmail_inventory_icon.png.
        /// </summary>
        internal static string bodyArmor_ayreimWarrior {
            get {
                return ResourceManager.GetString("bodyArmor/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/boots/Vaal_Greaves_inventory_icon.png.
        /// </summary>
        internal static string boots_ayreimWarrior {
            get {
                return ResourceManager.GetString("boots/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/gloves/Antique_Gauntlets_inventory_icon.png.
        /// </summary>
        internal static string gloves_ayreimWarrior {
            get {
                return ResourceManager.GetString("gloves/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/helmet/Close_Helmet_inventory_icon.png.
        /// </summary>
        internal static string helmet_ayreimWarrior {
            get {
                return ResourceManager.GetString("helmet/ayreimWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Splinter_of_Chayula_inventory_icon.png.
        /// </summary>
        internal static string magic_akashCrystal {
            get {
                return ResourceManager.GetString("magic/akashCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Imbued_Catalyst_inventory_icon.png.
        /// </summary>
        internal static string magic_akashicDust {
            get {
                return ResourceManager.GetString("magic/akashicDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Fertile_Catalyst_inventory_icon.png.
        /// </summary>
        internal static string magic_burnDust {
            get {
                return ResourceManager.GetString("magic/burnDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Splinter_of_Uul-Netol_inventory_icon.png.
        /// </summary>
        internal static string magic_earthCrystal {
            get {
                return ResourceManager.GetString("magic/earthCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Turbulent_Catalyst_inventory_icon.png.
        /// </summary>
        internal static string magic_eclipseDust {
            get {
                return ResourceManager.GetString("magic/eclipseDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Splinter_of_Xoph_inventory_icon.png.
        /// </summary>
        internal static string magic_fireCrystal {
            get {
                return ResourceManager.GetString("magic/fireCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Noxious_Catalyst_inventory_icon.png.
        /// </summary>
        internal static string magic_lifeDust {
            get {
                return ResourceManager.GetString("magic/lifeDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Accelerating_Catalyst_inventory_icon.png.
        /// </summary>
        internal static string magic_sproutDust {
            get {
                return ResourceManager.GetString("magic/sproutDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Unstable_Catalyst_inventory_icon.png.
        /// </summary>
        internal static string magic_starDust {
            get {
                return ResourceManager.GetString("magic/starDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Abrasive_Catalyst_inventory_icon.png.
        /// </summary>
        internal static string magic_sunsetDust {
            get {
                return ResourceManager.GetString("magic/sunsetDust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Vial_of_Transcendence_inventory_icon.png.
        /// </summary>
        internal static string magic_vialOfTranscendence {
            get {
                return ResourceManager.GetString("magic/vialOfTranscendence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Splinter_of_Esh_inventory_icon.png.
        /// </summary>
        internal static string magic_waterCrystal {
            get {
                return ResourceManager.GetString("magic/waterCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/magic/Splinter_of_Tul_inventory_icon.png.
        /// </summary>
        internal static string magic_windCrystal {
            get {
                return ResourceManager.GetString("magic/windCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/potions/Greater_Life_Flask_inventory_icon.png.
        /// </summary>
        internal static string potion_mediumHealth {
            get {
                return ResourceManager.GetString("potion/mediumHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/potions/small_dexterity.png.
        /// </summary>
        internal static string potion_smallDexterity {
            get {
                return ResourceManager.GetString("potion/smallDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/potions/Large_Life_Flask_inventory_icon.png.
        /// </summary>
        internal static string potion_smallHealth {
            get {
                return ResourceManager.GetString("potion/smallHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/potions/small_strength.png.
        /// </summary>
        internal static string potion_smallStrength {
            get {
                return ResourceManager.GetString("potion/smallStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Asparagus_Spear.png.
        /// </summary>
        internal static string regular_asparagus {
            get {
                return ResourceManager.GetString("regular/asparagus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Green_Bean.png.
        /// </summary>
        internal static string regular_bean {
            get {
                return ResourceManager.GetString("regular/bean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Blackberry.png.
        /// </summary>
        internal static string regular_blackberry {
            get {
                return ResourceManager.GetString("regular/blackberry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Carrot.png.
        /// </summary>
        internal static string regular_carrot {
            get {
                return ResourceManager.GetString("regular/carrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Cherry.png.
        /// </summary>
        internal static string regular_cherry {
            get {
                return ResourceManager.GetString("regular/cherry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Copper_Ore.png.
        /// </summary>
        internal static string regular_copperOre {
            get {
                return ResourceManager.GetString("regular/copperOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Cotton_Scrap.png.
        /// </summary>
        internal static string regular_cottonScrap {
            get {
                return ResourceManager.GetString("regular/cottonScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Fungus.png.
        /// </summary>
        internal static string regular_fungus {
            get {
                return ResourceManager.GetString("regular/fungus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/horn.png.
        /// </summary>
        internal static string regular_goatHorn {
            get {
                return ResourceManager.GetString("regular/goatHorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Gold_Ore.png.
        /// </summary>
        internal static string regular_goldOre {
            get {
                return ResourceManager.GetString("regular/goldOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Iron_Ore.png.
        /// </summary>
        internal static string regular_ironOre {
            get {
                return ResourceManager.GetString("regular/ironOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Jute_Scrap.png.
        /// </summary>
        internal static string regular_juteScrap {
            get {
                return ResourceManager.GetString("regular/juteScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Linen_Scrap.png.
        /// </summary>
        internal static string regular_linenScrap {
            get {
                return ResourceManager.GetString("regular/linenScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Mint_Leaf.png.
        /// </summary>
        internal static string regular_mint {
            get {
                return ResourceManager.GetString("regular/mint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Mithril_Ore.png.
        /// </summary>
        internal static string regular_mithrilOre {
            get {
                return ResourceManager.GetString("regular/mithrilOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Mushroom.png.
        /// </summary>
        internal static string regular_mushroom {
            get {
                return ResourceManager.GetString("regular/mushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Orichalcum_Ore.png.
        /// </summary>
        internal static string regular_orichalcumOre {
            get {
                return ResourceManager.GetString("regular/orichalcumOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Platinum_Ore.png.
        /// </summary>
        internal static string regular_platinumOre {
            get {
                return ResourceManager.GetString("regular/platinumOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Silk_Scrap.png.
        /// </summary>
        internal static string regular_silkScrap {
            get {
                return ResourceManager.GetString("regular/silkScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Spike.png.
        /// </summary>
        internal static string regular_spike {
            get {
                return ResourceManager.GetString("regular/spike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Strawberry.png.
        /// </summary>
        internal static string regular_strawberry {
            get {
                return ResourceManager.GetString("regular/strawberry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/fang.png.
        /// </summary>
        internal static string regular_wolveFang {
            get {
                return ResourceManager.GetString("regular/wolveFang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/regular/Wool_Scrap.png.
        /// </summary>
        internal static string regular_woolScrap {
            get {
                return ResourceManager.GetString("regular/woolScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný /items/weapon/Legion_Sword_inventory_icon.png.
        /// </summary>
        internal static string weapon_aresBlade {
            get {
                return ResourceManager.GetString("weapon/aresBlade", resourceCulture);
            }
        }
    }
}
