name: Client Build

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Pull LFS objects
      run: git lfs pull

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Restore
      run: dotnet restore MysticLegendsClient\MysticLegendsClient.csproj

    - name: Publish application
      run: dotnet publish MysticLegendsClient\MysticLegendsClient.csproj -c Release -o publish

    - name: Zip package
      run: Compress-Archive -Path .\publish\* -DestinationPath .\MysticLegendsClient.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          MysticLegendsClient.zip

